---
- name: play book to add alist of users
  hosts: webservers
  vars_files:
    - vars/vars.yml
  tasks:
   - name: addu sers
     ansible.builtin.user:
      name: "{{item.name}}"
      uid: "{{item.id}}"

      #if you want to delete
      state: absent 
      remove: yes
      ################################################
      
     loop: "{{user_list}}"


